language: php

## Run on container environment
sudo: false

env:
    - NETTE=2.1
    - NETTE=2.2
    - NETTE=2.3
    - NETTE=master

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    allow_failures:
        - php: hhvm
        - php: 7.0

before_install:
    - composer self-update
    - php tests/prepare-composer.php

install:
    - composer install --no-interaction --prefer-dist

script:
    - vendor/bin/tester tests -s -c tests/php-unix.ini -p php

after_failure:
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

cache:
  directories:
    - $HOME/.composer/cache