language: php

matrix:
    include:
        - php: 5.4
          env: dependencies=low
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: hhvm
    allow_failures:
        - php: hhvm

env:
    global:
        - dependencies=high

before_install:
    - composer self-update

install:
    - if [ "$dependencies" = "high" ]; then composer install --no-interaction --dev --prefer-source; fi

script:
    - if [ "$dependencies" = "low" ]; then composer update --no-interaction --dev --prefer-source --prefer-lowest --prefer-stable; fi
    - vendor/bin/tester tests -s -c tests/php-unix.ini -p php

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

